/**
 * Seed catalogue.
 *
 * Mirrors the client's dev fixture (`client/src/services/mockCatalogue.js`) so
 * flipping `USE_MOCK` off produces identical data. Once the API is live that
 * client fixture is a development-only convenience and can be deleted.
 *
 * Image URLs point at picsum placeholders; real imagery arrives with the CJ sync
 * in step 12.
 */
const image = (seed, w = 800, h = 1000) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

const categories = [
  { slug: 'electronics', name: 'Electronics', tagline: 'Sound, power and light', position: 1 },
  { slug: 'fashion', name: 'Fashion', tagline: 'Considered essentials', position: 2 },
  { slug: 'home-living', name: 'Home & Living', tagline: 'Objects for daily rituals', position: 3 },
  { slug: 'beauty', name: 'Beauty', tagline: 'Skincare and body care', position: 4 },
  { slug: 'accessories', name: 'Accessories', tagline: 'Watches, bags, eyewear', position: 5 },
  { slug: 'lifestyle', name: 'Lifestyle', tagline: 'Movement and recovery', position: 6 },
];

const products = [
  {
    slug: 'aura-noise-cancelling-headphones',
    sku: 'ZV-AUD-0001',
    name: 'Aura Noise-Cancelling Headphones',
    category: 'electronics',
    price: 349,
    compareAtPrice: 429,
    rating: 4.8,
    reviewCount: 1284,
    stock: 42,
    shortDescription:
      'Adaptive noise cancellation, 40-hour battery and a build that feels considered in every detail.',
    description:
      'Aura pairs a pair of custom 40mm drivers with adaptive cancellation that reads the room forty times a second. Memory-foam ear cushions are wrapped in protein leather, and the whole frame folds flat for travel. Tuned warm, so long sessions stay easy rather than tiring.',
    images: [image('aura-headphones'), image('aura-headphones-alt')],
    colors: [
      { name: 'Midnight Black', value: '#111111' },
      { name: 'Sandstone', value: '#C8B7A6' },
      { name: 'Silver', value: '#D5D7D9' },
    ],
    variants: [
      { name: 'Midnight Black', type: 'color', stock: 18, price: null },
      { name: 'Sandstone', type: 'color', stock: 14, price: null },
      { name: 'Silver', type: 'color', stock: 10, price: null },
    ],
    // Supplier-only. Never returned by any public endpoint.
    supplier: { productId: 'cj-1001', sku: 'CJ-AUD-1', costPrice: 168.5, shippingCost: 12.4, supplierStock: 210 },
    specifications: [
      ['Driver', '40mm custom dynamic'],
      ['Battery life', '40 hours with ANC on, 60 hours off'],
      ['Connectivity', 'Bluetooth 5.3, USB-C, 3.5mm'],
      ['Weight', '268 g'],
      ['In the box', 'Case, USB-C cable, 3.5mm cable'],
    ],
  },
  {
    slug: 'meridian-automatic-watch',
    sku: 'ZV-ACC-0002',
    name: 'Meridian Automatic Watch',
    category: 'accessories',
    price: 289,
    compareAtPrice: 340,
    rating: 4.7,
    reviewCount: 862,
    stock: 26,
    shortDescription: 'A 38mm automatic with a sapphire crystal and a brushed steel case that ages well.',
    description:
      'Meridian runs on a Japanese automatic movement with a 42-hour reserve. The dial is sunray-brushed with applied indices, and the case is 316L steel with a 50m water resistance. Sized at 38mm with a 19mm strap, so it sits comfortably on a smaller wrist.',
    images: [image('meridian-watch'), image('meridian-watch-alt')],
    colors: [
      { name: 'Steel / Slate', value: '#5B6068' },
      { name: 'Steel / Ivory', value: '#E6E0D4' },
    ],
    variants: [
      { name: 'Steel / Slate', type: 'color', stock: 15, price: null },
      { name: 'Steel / Ivory', type: 'color', stock: 11, price: null },
    ],
    supplier: { productId: 'cj-1002', sku: 'CJ-ACC-2', costPrice: 121.0, shippingCost: 9.8, supplierStock: 140 },
    specifications: [
      ['Movement', 'Japanese automatic, 42-hour reserve'],
      ['Case', '316L stainless steel, 38mm'],
      ['Crystal', 'Sapphire, anti-reflective coating'],
      ['Water resistance', '50 m / 5 ATM'],
      ['Strap', '19mm quick-release leather'],
    ],
  },
  {
    slug: 'lumen-desk-lamp',
    sku: 'ZV-HOM-0003',
    name: 'Lumen Desk Lamp',
    category: 'home-living',
    price: 129,
    compareAtPrice: 159,
    rating: 4.6,
    reviewCount: 431,
    stock: 8,
    shortDescription: 'Continuous dimming, a warm-to-cool range, and a weighted base that does not slide.',
    description:
      'Lumen uses a high-CRI LED behind a diffuser, so colour stays accurate even at the lowest setting. The arm holds any position without drift, and the touch strip on the base controls brightness and colour temperature from 2700K to 5000K.',
    images: [image('lumen-lamp'), image('lumen-lamp-alt')],
    colors: [
      { name: 'Bone', value: '#EDE9E2' },
      { name: 'Graphite', value: '#3A3A3A' },
    ],
    variants: [
      { name: 'Bone', type: 'color', stock: 5, price: null },
      { name: 'Graphite', type: 'color', stock: 3, price: null },
    ],
    supplier: { productId: 'cj-1003', sku: 'CJ-HOM-3', costPrice: 41.2, shippingCost: 8.5, supplierStock: 90 },
    specifications: [
      ['Light output', '450 lumens max'],
      ['Colour temperature', '2700K – 5000K, continuous'],
      ['CRI', '95+'],
      ['Reach', '52 cm from base'],
      ['Power', '9W USB-C'],
    ],
  },
  {
    slug: 'vero-ceramic-pour-over-set',
    sku: 'ZV-HOM-0004',
    name: 'Vero Ceramic Pour-Over Set',
    category: 'home-living',
    price: 68,
    compareAtPrice: null,
    rating: 4.9,
    reviewCount: 2140,
    stock: 64,
    shortDescription: 'Stoneware dripper, carafe and two coasters in a single glazed set.',
    description:
      'Thrown from a single stoneware body and finished in a satin glaze that resists staining. The spiral ribbing keeps the drawdown even, and the carafe is dishwasher safe. Designed to be left on the counter rather than put away.',
    images: [image('vero-pourover'), image('vero-pourover-alt')],
    colors: [{ name: 'Chalk', value: '#F1EDE6' }],
    variants: [],
    supplier: { productId: 'cj-1004', sku: 'CJ-HOM-4', costPrice: 19.4, shippingCost: 6.2, supplierStock: 400 },
    specifications: [
      ['Material', 'Stoneware, satin glaze'],
      ['Capacity', '600ml carafe, 2–4 cups'],
      ['Ridging', 'Spiral, 18 grooves'],
      ['Care', 'Dishwasher safe, not microwave'],
      ['Set', 'Dripper, carafe, 2 coasters'],
    ],
  },
  {
    slug: 'solstice-leather-tote',
    sku: 'ZV-FAS-0005',
    name: 'Solstice Leather Tote',
    category: 'fashion',
    price: 245,
    compareAtPrice: 310,
    rating: 4.7,
    reviewCount: 517,
    stock: 19,
    shortDescription: 'Full-grain leather with a soft structure that holds its shape without a rigid frame.',
    description:
      'Cut from full-grain leather with a vegetable-tanned finish, the Solstice slouches when full and stands upright when empty. Magnetic closure, one zipped interior pocket, and a suede-lined base that resists scuffing.',
    images: [image('solstice-tote'), image('solstice-tote-alt')],
    colors: [
      { name: 'Tan', value: '#B98B5E' },
      { name: 'Espresso', value: '#4A342A' },
      { name: 'Black', value: '#1A1A1A' },
    ],
    variants: [
      { name: 'Tan', type: 'color', stock: 9, price: null },
      { name: 'Espresso', type: 'color', stock: 6, price: null },
      { name: 'Black', type: 'color', stock: 4, price: null },
    ],
    supplier: { productId: 'cj-1005', sku: 'CJ-FAS-5', costPrice: 96.0, shippingCost: 14.0, supplierStock: 85 },
    specifications: [
      ['Material', 'Full-grain vegetable-tanned leather'],
      ['Dimensions', '38 × 30 × 14 cm'],
      ['Closure', 'Magnetic snap'],
      ['Interior', 'One zipped pocket, suede-lined base'],
      ['Strap drop', '24 cm'],
    ],
  },
  {
    slug: 'nimbus-running-shoes',
    sku: 'ZV-FAS-0006',
    name: 'Nimbus Running Shoes',
    category: 'fashion',
    price: 158,
    compareAtPrice: 195,
    rating: 4.5,
    reviewCount: 1893,
    stock: 73,
    shortDescription: 'A lightweight everyday trainer with a foam midsole that stays stable past 10km.',
    description:
      'The Nimbus uses a nitrogen-infused foam midsole under a breathable engineered knit upper. The outsole is rubber only where it needs to be, which keeps the shoe light without giving up grip. Weighs 238g in a size 9.',
    images: [image('nimbus-runner'), image('nimbus-runner-alt')],
    colors: [
      { name: 'Bone / Clay', value: '#E4DCD0' },
      { name: 'Slate / Volt', value: '#5F6B70' },
    ],
    sizes: ['EU 38', 'EU 39', 'EU 40', 'EU 41', 'EU 42', 'EU 43', 'EU 44', 'EU 45'],
    variants: [
      { name: 'Bone / Clay', type: 'color', stock: 24, price: null },
      { name: 'Slate / Volt', type: 'color', stock: 22, price: null },
    ],
    supplier: { productId: 'cj-1006', sku: 'CJ-FAS-6', costPrice: 52.8, shippingCost: 9.9, supplierStock: 320 },
    specifications: [
      ['Midsole', 'Nitrogen-infused foam'],
      ['Upper', 'Engineered recycled knit'],
      ['Outsole', 'Blown rubber, 4mm drop'],
      ['Weight', '238 g (size 9)'],
      ['Fit', 'True to size'],
    ],
  },
  {
    slug: 'halo-skincare-ritual-set',
    sku: 'ZV-BEA-0007',
    name: 'Halo Skincare Ritual Set',
    category: 'beauty',
    price: 118,
    compareAtPrice: 145,
    rating: 4.8,
    reviewCount: 3042,
    stock: 55,
    shortDescription: 'Cleanser, serum and barrier cream sized for travel and formulated without fragrance.',
    description:
      'Three steps, no filler. A low-pH cleanser, a niacinamide serum at 5%, and a barrier cream with ceramides and squalane. Fragrance-free, non-comedogenic, and tested on volunteers with sensitive skin.',
    images: [image('halo-skincare'), image('halo-skincare-alt')],
    colors: [],
    variants: [],
    supplier: { productId: 'cj-1007', sku: 'CJ-BEA-7', costPrice: 34.9, shippingCost: 6.4, supplierStock: 500 },
    specifications: [
      ['Includes', 'Cleanser 100ml, serum 30ml, barrier cream 50ml'],
      ['Key actives', 'Niacinamide 5%, ceramides, squalane'],
      ['Free from', 'Fragrance, essential oils, alcohol'],
      ['Suited to', 'Sensitive and combination skin'],
      ['Cruelty free', 'Yes'],
    ],
  },
  {
    slug: 'drift-essential-oil-diffuser',
    sku: 'ZV-HOM-0008',
    name: 'Drift Essential Oil Diffuser',
    category: 'home-living',
    price: 84,
    compareAtPrice: null,
    rating: 4.4,
    reviewCount: 726,
    stock: 3,
    shortDescription: 'A 300ml ultrasonic diffuser with a real timer and a lamp that can be switched off.',
    description:
      'Drift runs quietly enough to use in a bedroom, holds 300ml, and shuts down cleanly when the tank is empty. The warm lamp is independently switchable, so it can run through the night without light.',
    images: [image('drift-diffuser'), image('drift-diffuser-alt')],
    colors: [
      { name: 'White', value: '#F5F5F5' },
      { name: 'Sand', value: '#DCD2C4' },
    ],
    variants: [
      { name: 'White', type: 'color', stock: 2, price: null },
      { name: 'Sand', type: 'color', stock: 1, price: null },
    ],
    supplier: { productId: 'cj-1008', sku: 'CJ-HOM-8', costPrice: 24.6, shippingCost: 7.1, supplierStock: 160 },
    specifications: [
      ['Capacity', '300ml'],
      ['Runtime', 'Up to 10 hours intermittent'],
      ['Noise level', 'Under 25 dB'],
      ['Controls', 'Touch, 1/3/6 hour timer'],
      ['Lamp', 'Warm glow, independently switchable'],
    ],
  },
  {
    slug: 'terra-ceramic-tableware-set',
    sku: 'ZV-HOM-0009',
    name: 'Terra Ceramic Tableware Set',
    category: 'home-living',
    price: 152,
    compareAtPrice: 189,
    rating: 4.6,
    reviewCount: 388,
    stock: 21,
    shortDescription: 'Sixteen pieces of reactive-glazed stoneware for everyday use.',
    description:
      'Sixteen pieces — four place settings, each with a dinner plate, side plate, bowl and mug. The reactive glaze means no two pieces are identical. Chip-resistant edges, microwave safe.',
    images: [image('terra-tableware'), image('terra-tableware-alt')],
    colors: [
      { name: 'Ash', value: '#B4B8B2' },
      { name: 'Clay', value: '#B07C5E' },
    ],
    variants: [
      { name: 'Ash', type: 'color', stock: 12, price: null },
      { name: 'Clay', type: 'color', stock: 9, price: null },
    ],
    supplier: { productId: 'cj-1009', sku: 'CJ-HOM-9', costPrice: 58.0, shippingCost: 15.5, supplierStock: 120 },
    specifications: [
      ['Pieces', '16 (4 place settings)'],
      ['Material', 'Stoneware, reactive glaze'],
      ['Microwave safe', 'Yes'],
      ['Care', 'Dishwasher safe'],
      ['Note', 'Reactive glaze makes every piece unique'],
    ],
  },
  {
    slug: 'pulse-fitness-band',
    sku: 'ZV-LIF-0010',
    name: 'Pulse Fitness Band',
    category: 'lifestyle',
    price: 99,
    compareAtPrice: 129,
    rating: 4.3,
    reviewCount: 2210,
    stock: 96,
    shortDescription: 'Fourteen-day battery, continuous heart rate and a swim-proof chassis.',
    description:
      'Pulse tracks heart rate, sleep stages and 90 workout types. The 5ATM chassis means it survives pool and open-water swims. Fourteen days per charge, and the band itself weighs 24g.',
    images: [image('pulse-band'), image('pulse-band-alt')],
    colors: [],
    sizes: [{ name: 'S / M / L' }],
    variants: [],
    supplier: { productId: 'cj-1010', sku: 'CJ-LIF-10', costPrice: 28.4, shippingCost: 5.9, supplierStock: 800 },
    specifications: [
      ['Battery', '14 days typical'],
      ['Water resistance', '5 ATM, swim-proof'],
      ['Sensors', 'Heart rate, SpO2, sleep stages'],
      ['Workout modes', '90'],
      ['Weight', '24 g'],
    ],
  },
  {
    slug: 'mist-wool-overshirt',
    sku: 'ZV-FAS-0011',
    name: 'Mist Wool Overshirt',
    category: 'fashion',
    price: 175,
    compareAtPrice: null,
    rating: 4.7,
    reviewCount: 642,
    stock: 34,
    shortDescription: 'A heavy wool-overshirt cut that works as a light jacket through autumn.',
    description:
      'Woven from a wool-cotton blend at 380gsm, with a clean placket and two deep patch pockets. It layers over a tee or a fine knit and reads as a jacket without the weight of one.',
    images: [image('mist-overshirt'), image('mist-overshirt-alt')],
    colors: [
      { name: 'Fog', value: '#A8ADB0' },
      { name: 'Olive', value: '#5A6048' },
      { name: 'Ink', value: '#242A33' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    variants: [
      { name: 'Fog', type: 'color', stock: 14, price: null },
      { name: 'Olive', type: 'color', stock: 12, price: null },
      { name: 'Ink', type: 'color', stock: 8, price: null },
    ],
    supplier: { productId: 'cj-1011', sku: 'CJ-FAS-11', costPrice: 63.5, shippingCost: 11.2, supplierStock: 210 },
    specifications: [
      ['Material', 'Wool-cotton blend, 380gsm'],
      ['Fit', 'Relaxed, layer-friendly'],
      ['Pockets', 'Two deep patch'],
      ['Care', 'Dry clean or cold wash'],
      ['Origin', 'Woven in Portugal'],
    ],
  },
  {
    slug: 'onyx-sunglasses',
    sku: 'ZV-ACC-0012',
    name: 'Onyx Sunglasses',
    category: 'accessories',
    price: 210,
    compareAtPrice: 265,
    rating: 4.6,
    reviewCount: 355,
    stock: 4,
    shortDescription: 'Hand-polished acetate frames with polarised mineral lenses.',
    description:
      'Cut from Italian acetate and polished by hand for fourteen hours. The mineral lenses are polarised and treated with an anti-reflective coating. Comes with a hard case and a folded microfibre cloth.',
    images: [image('onyx-sunglasses'), image('onyx-sunglasses-alt')],
    colors: [
      { name: 'Black', value: '#141414' },
      { name: 'Tortoise', value: '#6B4A2E' },
    ],
    variants: [
      { name: 'Black', type: 'color', stock: 2, price: null },
      { name: 'Tortoise', type: 'color', stock: 2, price: null },
    ],
    supplier: { productId: 'cj-1012', sku: 'CJ-ACC-12', costPrice: 43.0, shippingCost: 7.8, supplierStock: 70 },
    specifications: [
      ['Frame', 'Italian acetate, hand-polished'],
      ['Lenses', 'Polarised mineral glass'],
      ['Width', '148mm'],
      ['Includes', 'Hard case, microfibre cloth'],
      ['UV', '100% UVA/UVB'],
    ],
  },
];

/** Users. Passwords are bcrypt hashes generated by the seed script. */
const users = [
  {
    email: 'demo@zavora.com',
    password: 'zavora1234',
    firstName: 'Alex',
    lastName: 'Moreau',
    phone: '+1 555 000 1234',
    role: 'customer',
  },
  {
    email: 'admin@zavora.com',
    password: 'zavora-admin-2026',
    firstName: 'Sam',
    lastName: 'Rivera',
    phone: '+1 555 000 9999',
    role: 'admin',
  },
];

const addresses = [
  {
    email: 'demo@zavora.com',
    label: 'Home',
    firstName: 'Alex',
    lastName: 'Moreau',
    phone: '+1 555 000 1234',
    country: 'US',
    state: 'California',
    city: 'San Francisco',
    address1: '1200 Market Street',
    address2: 'Apt 4B',
    postalCode: '94103',
    isDefault: 1,
  },
  {
    email: 'demo@zavora.com',
    label: 'Office',
    firstName: 'Alex',
    lastName: 'Moreau',
    phone: '+1 555 000 1234',
    country: 'DE',
    state: 'Berlin',
    city: 'Berlin',
    address1: 'Torstrasse 1',
    address2: '',
    postalCode: '10119',
    isDefault: 0,
  },
];

const reviews = [
  {
    slug: 'aura-noise-cancelling-headphones',
    rating: 5,
    title: 'Better than I expected',
    body: 'Ordered on a Tuesday and it arrived by Friday. The finish is genuinely nice in person — it does not feel like something that cost this little. Two weeks in and no complaints at all.',
    authorName: 'Marta K.',
    country: 'DE',
    isVerified: 1,
  },
  {
    slug: 'aura-noise-cancelling-headphones',
    rating: 5,
    title: 'Exactly as described',
    body: 'I was sceptical about ordering from an international store but the tracking worked the whole way and I could see it clear customs. Product matches the photos closely.',
    authorName: 'Daniel R.',
    country: 'GB',
    isVerified: 1,
  },
  {
    slug: 'aura-noise-cancelling-headphones',
    rating: 4,
    title: 'Very good, one small note',
    body: 'No complaints about quality. Took a day longer than the estimate to reach me, which the tracking page did explain. Would happily buy again.',
    authorName: 'Aiko T.',
    country: 'JP',
    isVerified: 1,
  },
  {
    slug: 'nimbus-running-shoes',
    rating: 5,
    title: 'Third pair I have bought',
    body: 'Bought this after wearing mine for a year. Same sizing, same cushioning. Packaging is minimal which I appreciate.',
    authorName: 'Sofia L.',
    country: 'ES',
    isVerified: 0,
  },
  {
    slug: 'halo-skincare-ritual-set',
    rating: 5,
    title: 'No irritation at all',
    body: 'I react to almost everything and this did nothing at all for six weeks. The serum is the one I would repurchase.',
    authorName: 'Nadia B.',
    country: 'FR',
    isVerified: 1,
  },
];

/**
 * Demo orders so the customer dashboard has real history immediately.
 * `lines` reference product slugs; the seed resolves them.
 */
const orders = [
  {
    orderNumber: 'ZV-8KQ2M1-447',
    email: 'demo@zavora.com',
    status: 'in_transit',
    paymentStatus: 'paid',
    daysAgo: 2,
    country: 'DE',
    shippingMethod: 'express',
    carrier: 'DHL Express',
    trackingNumber: 'JD0146000038284712',
    deliveryInDays: 2,
    address: { firstName: 'Alex', lastName: 'Moreau', phone: '+49 30 000000', country: 'DE', state: 'Berlin', city: 'Berlin', address1: 'Torstrasse 1', address2: '', postalCode: '10119' },
    lines: [
      { slug: 'aura-noise-cancelling-headphones', variant: 'Midnight Black', quantity: 1 },
      { slug: 'halo-skincare-ritual-set', variant: null, quantity: 1 },
    ],
  },
  {
    orderNumber: 'ZV-3PL8W7-102',
    email: 'demo@zavora.com',
    status: 'shipped',
    paymentStatus: 'paid',
    daysAgo: 9,
    country: 'US',
    shippingMethod: 'standard',
    carrier: 'UPS',
    trackingNumber: '1Z999AA10123456784',
    deliveryInDays: 4,
    address: { firstName: 'Alex', lastName: 'Moreau', phone: '+1 555 000 1234', country: 'US', state: 'California', city: 'San Francisco', address1: '1200 Market Street', address2: 'Apt 4B', postalCode: '94103' },
    lines: [{ slug: 'meridian-automatic-watch', variant: 'Steel / Slate', quantity: 1 }],
  },
  {
    orderNumber: 'ZV-6TR4X9-881',
    email: 'demo@zavora.com',
    status: 'delivered',
    paymentStatus: 'paid',
    daysAgo: 26,
    country: 'GB',
    shippingMethod: 'standard',
    carrier: 'FedEx',
    trackingNumber: '7749 2200 3398',
    deliveryInDays: -19,
    address: { firstName: 'Alex', lastName: 'Moreau', phone: '+44 20 0000 0000', country: 'GB', state: 'Greater London', city: 'London', address1: '14 Shoreditch High St', address2: '', postalCode: 'E1 6JE' },
    lines: [
      { slug: 'vero-ceramic-pour-over-set', variant: null, quantity: 2 },
      { slug: 'drift-essential-oil-diffuser', variant: 'Sand', quantity: 1 },
    ],
  },
  {
    orderNumber: 'ZV-9HN5J2-336',
    email: 'demo@zavora.com',
    status: 'delivered',
    paymentStatus: 'paid',
    daysAgo: 41,
    country: 'NL',
    shippingMethod: 'standard',
    carrier: 'PostNL',
    trackingNumber: '3SABC123456789',
    deliveryInDays: -34,
    address: { firstName: 'Alex', lastName: 'Moreau', phone: '+31 20 000 0000', country: 'NL', state: 'Noord-Holland', city: 'Amsterdam', address1: 'Damrak 12', address2: '', postalCode: '1012 LG' },
    lines: [{ slug: 'mist-wool-overshirt', variant: 'Fog', quantity: 1 }],
  },
  {
    orderNumber: 'ZV-2WQ7B3-590',
    email: 'demo@zavora.com',
    status: 'processing',
    paymentStatus: 'paid',
    daysAgo: 3,
    country: 'US',
    shippingMethod: 'standard',
    carrier: null,
    trackingNumber: null,
    deliveryInDays: 4,
    address: { firstName: 'Alex', lastName: 'Moreau', phone: '+1 555 000 1234', country: 'US', state: 'California', city: 'San Francisco', address1: '1200 Market Street', address2: 'Apt 4B', postalCode: '94103' },
    lines: [{ slug: 'solstice-leather-tote', variant: 'Tan', quantity: 1 }],
  },
];

const settings = [
  ['store.name', 'ZAVORA', 'general'],
  ['store.currency', 'USD', 'general'],
  ['store.locale', 'en-US', 'general'],
  ['pricing.default_margin_percent', '35', 'pricing'],
  ['pricing.free_shipping_threshold', '150', 'pricing'],
  ['pricing.standard_shipping_fee', '6.95', 'pricing'],
  ['cj.account_email', 'REPLACE_ME_cj_email', 'cj'],
  ['cj.api_token', 'REPLACE_ME_cj_api_token', 'cj'],
];

module.exports = { categories, products, users, addresses, reviews, orders, settings, image };